### ISSUE TITLE
make up_c BRANCH=rabbitmq_v3_5_4 fails due to lack of a respective tag in 'cowlib-wrapper'

### ISSUE THREAD

**Issue by romanek-adam** [rabbitmq/rabbitmq-public-umbrella#31]
Hi, I followed the "Getting started" section from http://www.rabbitmq.com/plugin-development.html, i.e.:

    git clone https://github.com/rabbitmq/rabbitmq-public-umbrella.git
    cd rabbitmq-public-umbrella
    make co
    make up_c BRANCH=rabbitmq_v3_5_4

The output ends like this:

    (cd cowlib-wrapper && git fetch -p && git checkout rabbitmq_v3_5_4 && (! git symbolic-ref -q HEAD || git pull --ff-only))
    error: pathspec 'rabbitmq_v3_5_4' did not match any file(s) known to git.
    make: *** [cowlib-wrapper+named_update] Error 1

**Comment by michaelklishin** [comment]
With the recent switch to erlang.mk this is no longer relevant (even for `stable`, which is less than 1 month away from being replaced with current master).
