### ISSUE TITLE
Commit message cannot include the word "commit"

### ISSUE THREAD

**Issue by gotthardp** [rabbitmq/rabbitmq-public-umbrella#32]
This is funny. The UPSTREAM_SHORT_HASH construction (do-package.mk:267) uses the following command `git --git-dir=$(CLONE_DIR)/.git log -n 1 HEAD | grep commit | cut -b 8-14` >$$@`.

When the git commit message includes the word "commit", the grep above produces two lines

```
commit a0fc3cf6b2dc1fda2ca700b79441a852988a5e29
    Forgot to commit tests.
```

and the short hash becomes invalid.

It would be safer to use `grep commit | head -n 1`.

**Comment by gerhard** [comment]
Expired
