### ISSUE TITLE
Change RABBITMQ_REPO_BASE to use ssh

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-public-umbrella#33]
Or at least make it an option. It's very annoying to have to deal with the mess that is per-app tokens and keychain helpers. None of our team work in environments where SSH is blocked, so I see no reason to use https in our case.

**Comment by dumbbell** [comment]
The URL of the dependencies is now inferred from the current project's "origin" remote URL. So if you use the GitHub SSH access, dependencies will be fetched using the same method.
