### ISSUE TITLE
common.mk (pre-erlang.mk) not compatible with GNU make 4.0?

### ISSUE THREAD

**Issue by gotthardp** [rabbitmq/rabbitmq-public-umbrella#36]
A user with Ubuntu 15.04 and GNU make 4.0 got the following error when building a plugin with the 3.5.x rabbitmq-umbrella:
../common.mk:10: **\* GNU make version 3.81 required.

After changing REQUIRED_MAKE_VERSION in common.mk:7 to 4.0 it compiled successfully.

I'm not sure you want to solve it since this problems disappears in 3.6.x, but still it's worth reporting I guess.

**Comment by dumbbell** [comment]
Hmm, this is strange. I'm using GNU Make 4.1 for a long time and used 4.0 before without problem.

Could you please check the value of `$(MAKE_VERSION)` and the output of sort(1)? You can use the following lines before the check in `common.mk`:
```
$(info MAKE_VERSION=$(MAKE_VERSION))
$(info $(shell ( echo "$(MAKE_VERSION)" ; echo "$(REQUIRED_MAKE_VERSION)" ) | sort -t. -n))
```

**Comment by gotthardp** [comment]
The output is:
```
MAKE_VERSION=4.0
4.0 3.81
../common.mk:13: *** GNU make version 3.81 required.  Останов.
```
Could it be caused by the Russian (or similar) environment?

**Comment by michaelklishin** [comment]
@gotthardp you can try with a different locale, e.g. by temporarily overriding `LANG` and `LC_*` env variables.

    LANG="ru_RU.UTF-8" make

works for me. Can you post what

    printenv | grep "LC_"
    printenv LANG

output?

**Comment by gotthardp** [comment]
Based on a report from @ArtemLubimov:

LANG="ru_RU.UTF-8" make
   MAKE_VERSION=4.0
   3.81 4.0

printenv | grep "LC_"
   Nothing

printenv LANG
   ru_UA.UTF-8

**Comment by michaelklishin** [comment]
LANG="ru_RU.UTF-8" make

on Ubuntu 15.04 (which has make 4.0) works for me in `rabbit_common`, `rabbit`, and so on.

**Comment by michaelklishin** [comment]
Scratch that, I'm trying with master and the report is for `3.5.x`. Yeah, I'm not sure if this is worth spending time on. I'll leave this to @dumbbell.

**Comment by dumbbell** [comment]
Anyway, we use sort(1) without setting `LC_COLLATE=C` so the result is unreliable. Can you try to add `LC_COLLATE=C` in front of sort(1) in the Makefile and test again?

**Comment by gotthardp** [comment]
Positive. :) When sort is prefixed by `LC_COLLATE=C` everything works fine.

**Comment by gerhard** [comment]
Expired, re-open if still relevant.
