### ISSUE TITLE
make run-broker fails

### ISSUE THREAD

**Issue by deadtrickster** [rabbitmq/rabbitmq-public-umbrella#37]
probably related to #34 
```
Error: No Makefile to build dependency ...rabbitmq-public-umbrella/deps/rabbitmq_website.
erlang.mk:4066: recipe for target 'deps' failed
```

A couple of month ago everything was ok :-/

**Comment by michaelklishin** [comment]
I'd recommend cloning the umbrella and doing `make co` from scratch.

**Comment by deadtrickster** [comment]
Sadly that's what I did.

**Comment by deadtrickster** [comment]
Update:

I added Makefile with empty goal. New error:

```
 GEN    dist
make[1]: Entering directory '....rabbitmq-public-umbrella'
 DIST   plugins/amqp_client.ez

zip error: Nothing to do! (try: zip -q -r amqp_client.ez . -i amqp_client)
.....rabbitmq-public-umbrella/deps/rabbit_common/mk/rabbitmq-dist.mk:126: recipe for target 'plugins/amqp_client.ez' failed
```

btw it won't event start without RABBIT_VSN. looks like default isn't working. Tried on master and stable. Not sure it's not my setup now. This can't be that broken :-).

**Comment by michaelklishin** [comment]
I re-create my Linux VM every few weeks and haven't run into this. I have 2 umbrellas per machine/OS.

**Comment by deadtrickster** [comment]
Sorry for the noise. looks like I ran make at the umbrella root not deps/rabbit. Too much coffee :-)
