### ISSUE TITLE
Current Erlang.mk can't build subfolders 

### ISSUE THREAD

**Issue by deadtrickster** [rabbitmq/rabbitmq-public-umbrella#39]
As @essen  confirmed in https://github.com/ninenines/erlang.mk/issues/556 current erlang.mk have troubles building projects with subfolders in src. Please update erlang.mk once the issue resolved.
Thanks

**Comment by essen** [comment]
For the sake of clarity it's only when projects define their own behaviors/parse_transforms and those behaviors/pts are also in a subfolder.

**Comment by deadtrickster** [comment]
Workaround: 
 - replace erlank.mk in plugin folder with newly build one. 
 - run make - this will generate "new" <depname>.d file for plugin dependency
 - remove COMPILE_FIRST line from <depname>.d
 - revert erlang.mk and run make - this might replace our patched <depname>.d if so restore it
