### ISSUE TITLE
Mismatch in ranch version for release rabbitmq v3.6.10

### ISSUE THREAD

**Issue by everydaysasaturday** [rabbitmq/rabbitmq-public-umbrella#50]
Rabbitmq release version: 3.6.10

As defined in rabbitmq-components.mk in dep_ranch_commit is set to 1.3.1.

The ranch version in ranch's (in ninenines) Makefile (PROJECT_VERSION) is set to 1.3.0 for this ranch 1.3.1 release.

This generated a bit of uncertainty on what I was doing wrong because triggering make dist in 3.6.10 mqtt (and I believe in all the plugins) I saw ranch-1.3.0 being build.

So even though the generated .ez ranch is 1.3.1 it's wrong PROJECT_VERSION builds it as ranch-1.3.0.ez.

Don't know is it anymore important as the master has ranch 1.3.2 defined and it has the right PROJECT_VERSION (1.3.2).

Fix would be to just define the dep_ranch_commit to 1.3.2  in rabbitmq-components.mk and the right version number would be available for the updated release.

Thanks.

**Comment by michaelklishin** [comment]
Thanks. IIRC Ranch in 1.3.0/1.3.1 had an issue with a version mismatching the tag

`rabbitmq-components.mk` does not reside in this repository (it's copied here every time we update the file). We will upgrade `stable` to Ranch 1.3.2 and try 1.4.0 for master some time soon.

**Comment by michaelklishin** [comment]
By the way, when you build a plugin from source you don't need to distributed the Ranch `.ez` with it since it's provided by the broker and having two Ranch versions on code path is not a good idea.

**Comment by everydaysasaturday** [comment]
Yep, the thing was only that I saw the ranch 1.3.0 being built with make dist VERSION=3.6.10 into plugins folder and THAT made me think that I was doing something wrong ... which was not the case.
